volumes:
  postgres_data_lingvo:
    driver: local

services:
  postgres_lingvo:
    container_name: postgres_lingvo
    image: postgres:15
    ports:
      - "${POSTGRESQL_PORT}:${POSTGRESQL_PORT}"
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    volumes:      
      - postgres_data_lingvo:/var/lib/postgresql/data
    restart: unless-stopped
  pgadmin_lingvo:
    container_name: pgadmin_lingvo
    image: dpage/pgadmin4:8.9
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT}
    depends_on:
      - postgres_lingvo
    restart: unless-stopped
